### PR TITLE
Property indexed keyframes

### PR DESCRIPTION
**Pull request by shans**
Introduces concept of property indexed keyframes (https://lists.w3.org/Archives/Public/public-fx/2015JanMar/0048.html item 6)

### CODE REVIEW

**Comment by shans** [comment]
This patch currently depends on KeyframeList (#80).

**Comment by birtles** [comment]
Thanks for doing this. Do you mind if I take a little while before reviewing this? The next two weeks are a bit overloaded. Feel free to chase me up here though if it's taking too long.

**Comment by shans** [comment]
Sure, no problems. I mainly wanted to discharge the AI.

**Comment by birtles** [comment]
I rebased this and was going to merge it but I noticed a few issues I think we need to resolve first.
I've added the rebased version with a bunch of fixups and issues as a separate branch: https://github.com/w3c/web-animations/tree/shans-propertyIndexedKeyframes

The main one is we probably need to change the signature of all the methods that take a set of keyframes to take a PropertyIndexedKeyframe or something of that sort. Other than that, we need to tighten up the algorithm for reading that object to be more explicit about what operations it uses.

**Comment by shans** [comment]
Awesome!

I'll take a look at the branch midweek and see what I can do to improve
things.

Cheers,
    -Shane

**Pull request closed without merging**
