### PR TITLE
Add a link to web-platform-tests to the top of the spec

### PR DESCRIPTION
**Pull request by foolip**
Many other specs that have something similar:
https://fetch.spec.whatwg.org/
https://w3c.github.io/IndexedDB/
https://notifications.spec.whatwg.org/
https://w3c.github.io/ServiceWorker/
https://webaudio.github.io/web-audio-api/
https://xhr.spec.whatwg.org/

### CODE REVIEW

**Comment by foolip** [comment]
I was looking at which directories in web-platform-tests was the most active so far in 2017, and web-animations was fairly high up on the list, so I thought leading more readers there would be a good idea.

**Comment by birtles** [comment]
Thanks Philip! Much appreciated!

**Comment by foolip** [comment]
That was fast, thanks! Following largely the same reasoning, would something like https://github.com/w3c/webappsec-csp/pull/230 make sense for Web Animations? I'm not particularly familiar with how the group currently works, but https://github.com/w3c/web-platform-tests/tree/master/web-animations looks quite well maintained, and starting with such an approach to normative changes is much easier if the test suite is already in good shape. WDYT?

**Comment by birtles** [comment]
Yes, that would make sense. There test suite needs some work (we're trying to arrange it to better line up with the spec sections) but generally I try to make spec changes and test changes hand-in-hand.

**Pull request merged**
